# Generated by Django 2.2.2 on 2019-07-04 01:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseManagement',
            fields=[
                ('course_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('credit', models.IntegerField()),
                ('session', models.CharField(max_length=100)),
                ('prerequisite', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_id', models.IntegerField()),
                ('full_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('enrolled_year', models.DateTimeField(default=datetime.datetime(2019, 7, 4, 7, 14, 32, 585373))),
                ('enrolled_session', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=40)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2019, 7, 4, 7, 14, 32, 585373))),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
