# Generated by Django 2.2.2 on 2019-07-04 01:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAuthentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmanagement',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 7, 14, 51, 989085)),
        ),
        migrations.AlterField(
            model_name='studentmanagement',
            name='enrolled_year',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 7, 14, 51, 989085)),
        ),
    ]
