# Generated by Django 2.2.2 on 2019-07-04 01:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAuthentication', '0003_auto_20190704_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmanagement',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 7, 17, 32, 200708)),
        ),
        migrations.AlterField(
            model_name='studentmanagement',
            name='enrolled_year',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 7, 17, 32, 200708)),
        ),
    ]
