# Generated by Django 2.2.2 on 2019-07-04 01:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAuthentication', '0005_auto_20190704_0726'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Firebase',
            new_name='FirebaseDatabase',
        ),
        migrations.AlterField(
            model_name='studentmanagement',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 7, 36, 18, 652656)),
        ),
        migrations.AlterField(
            model_name='studentmanagement',
            name='enrolled_year',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 7, 36, 18, 652656)),
        ),
    ]
