# Generated by Django 2.2.2 on 2019-07-04 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAuthentication', '0007_auto_20190704_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='firebasedatabase',
            name='extra_name',
            field=models.CharField(default=None, max_length=299),
        ),
        migrations.AlterField(
            model_name='studentmanagement',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 13, 0, 50, 520743)),
        ),
        migrations.AlterField(
            model_name='studentmanagement',
            name='enrolled_year',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 13, 0, 50, 520743)),
        ),
    ]
