# Generated by Django 2.2.2 on 2019-07-04 07:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAuthentication', '0008_auto_20190704_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subfirebase',
            name='names',
        ),
        migrations.AddField(
            model_name='firebasedatabase',
            name='fori',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='djangoAuthentication.subfirebase'),
        ),
        migrations.AddField(
            model_name='subfirebase',
            name='extra_names',
            field=models.CharField(default=None, max_length=299),
        ),
        migrations.AlterField(
            model_name='studentmanagement',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 13, 8, 23, 115843)),
        ),
        migrations.AlterField(
            model_name='studentmanagement',
            name='enrolled_year',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 13, 8, 23, 114844)),
        ),
    ]
