# Generated by Django 2.2.2 on 2019-07-04 07:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAuthentication', '0009_auto_20190704_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firebasedatabase',
            name='fori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoAuthentication.subfirebase'),
        ),
        migrations.AlterField(
            model_name='studentmanagement',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 13, 9, 34, 316327)),
        ),
        migrations.AlterField(
            model_name='studentmanagement',
            name='enrolled_year',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 13, 9, 34, 316327)),
        ),
    ]
