# Generated by Django 2.2.2 on 2019-07-05 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAuthentication', '0011_auto_20190705_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firebasedatabase',
            name='fori',
        ),
    ]
