# Generated by Django 2.2.2 on 2019-08-04 02:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAuthentication', '0013_auto_20190708_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmanagement',
            name='id',
        ),
        migrations.AlterField(
            model_name='studentmanagement',
            name='date_created',
            field=models.DateField(default=datetime.date(2019, 8, 4)),
        ),
        migrations.AlterField(
            model_name='studentmanagement',
            name='enrolled_year',
            field=models.DateField(default=datetime.date(2019, 8, 4)),
        ),
        migrations.AlterField(
            model_name='studentmanagement',
            name='university_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
