# Generated by Django 2.2.2 on 2019-08-05 02:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAuthentication', '0014_auto_20190804_0842'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FirebaseDatabase',
        ),
        migrations.DeleteModel(
            name='subfirebase',
        ),
        migrations.AlterField(
            model_name='studentmanagement',
            name='date_created',
            field=models.DateField(default=datetime.date(2019, 8, 5)),
        ),
        migrations.AlterField(
            model_name='studentmanagement',
            name='enrolled_year',
            field=models.DateField(default=datetime.date(2019, 8, 5)),
        ),
    ]
