# Generated by Django 2.2.2 on 2019-08-05 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAuthentication', '0015_auto_20190805_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('grades', models.CharField(max_length=299)),
                ('status', models.CharField(max_length=288)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoAuthentication.CourseManagement')),
                ('university_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoAuthentication.StudentManagement')),
            ],
        ),
    ]
