# Generated by Django 2.2.2 on 2019-08-05 03:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAuthentication', '0016_grademanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemanagement',
            name='deadline',
            field=models.DateField(default=datetime.date(2019, 8, 5)),
        ),
    ]
