# Generated by Django 2.2.2 on 2019-08-05 03:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAuthentication', '0017_coursemanagement_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemanagement',
            name='deadline',
        ),
        migrations.CreateModel(
            name='DeadLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date(2019, 8, 5))),
                ('end_date', models.DateField(default=datetime.date(2019, 8, 5))),
                ('course_code', models.ForeignKey(on_delete=models.Model, to='djangoAuthentication.CourseManagement')),
            ],
        ),
    ]
