# Generated by Django 2.2.2 on 2019-08-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAuthentication', '0021_auto_20190806_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemanagement',
            name='prerequisite',
            field=models.CharField(default=None, max_length=299),
        ),
        migrations.AlterField(
            model_name='statustable',
            name='session',
            field=models.CharField(max_length=299),
        ),
        migrations.AlterField(
            model_name='statustable',
            name='status',
            field=models.CharField(max_length=299),
        ),
        migrations.DeleteModel(
            name='Prerequisite',
        ),
    ]
