# Generated by Django 2.2.2 on 2019-08-06 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAuthentication', '0024_auto_20190806_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmanagement',
            name='status',
        ),
    ]
