# Generated by Django 2.2.2 on 2019-08-07 03:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAuthentication', '0025_remove_studentmanagement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='grademanagement',
            name='internal_marks',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='grademanagement',
            name='total_marks',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='end_date',
            field=models.DateField(default=datetime.date(2019, 8, 7)),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='start_date',
            field=models.DateField(default=datetime.date(2019, 8, 7)),
        ),
        migrations.AlterField(
            model_name='grademanagement',
            name='marks',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='studentmanagement',
            name='date_created',
            field=models.DateField(default=datetime.date(2019, 8, 7)),
        ),
        migrations.AlterField(
            model_name='studentmanagement',
            name='enrolled_year',
            field=models.DateField(default=datetime.date(2019, 8, 7)),
        ),
    ]
