# Generated by Django 2.2.2 on 2019-08-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAuthentication', '0026_auto_20190807_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmanagement',
            name='current_year',
            field=models.IntegerField(default=1),
        ),
    ]
