# Generated by Django 2.2.2 on 2019-08-09 02:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAuthentication', '0027_studentmanagement_current_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemanagement',
            name='credit',
            field=models.IntegerField(max_length=1),
        ),
        migrations.AlterField(
            model_name='coursemanagement',
            name='year',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='end_date',
            field=models.DateField(default=datetime.date(2019, 8, 9)),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='start_date',
            field=models.DateField(default=datetime.date(2019, 8, 9)),
        ),
        migrations.AlterField(
            model_name='studentmanagement',
            name='date_created',
            field=models.DateField(default=datetime.date(2019, 8, 9)),
        ),
        migrations.AlterField(
            model_name='studentmanagement',
            name='enrolled_year',
            field=models.DateField(default=datetime.date(2019, 8, 9)),
        ),
        migrations.AlterUniqueTogether(
            name='coursemanagement',
            unique_together={('course_code', 'prerequisite')},
        ),
    ]
