# Generated by Django 2.2.2 on 2019-08-09 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAuthentication', '0030_auto_20190809_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=200)),
                ('session_year', models.IntegerField(max_length=4)),
                ('session_session', models.CharField(max_length=100)),
                ('session_credit', models.IntegerField(max_length=1)),
                ('Offered', models.BooleanField()),
                ('courseCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoAuthentication.CourseManagement')),
            ],
        ),
    ]
