# Generated by Django 2.2.2 on 2019-08-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAuthentication', '0031_sessiontable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiontable',
            name='Offered',
            field=models.CharField(max_length=3),
        ),
    ]
