# Generated by Django 2.2.2 on 2019-08-11 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAuthentication', '0033_auto_20190811_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoAuthentication.CourseManagement')),
                ('univ_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoAuthentication.StudentManagement')),
            ],
        ),
    ]
