# Generated by Django 2.2.2 on 2019-08-13 06:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAuthentication', '0035_auto_20190813_0742'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionCourseTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_session', models.CharField(max_length=100)),
                ('course_credit', models.IntegerField(max_length=1)),
                ('Offered', models.CharField(max_length=3)),
                ('courseCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoAuthentication.CourseManagement')),
            ],
        ),
        migrations.CreateModel(
            name='SessionNameTable',
            fields=[
                ('session_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('session_year', models.IntegerField(max_length=4)),
                ('date_created', models.DateField(default=datetime.date(2019, 8, 13))),
                ('max_credit', models.IntegerField()),
                ('start_date', models.DateField(default=datetime.date(2019, 8, 13))),
                ('end_date', models.DateField(default=datetime.date(2019, 8, 13))),
            ],
        ),
        migrations.RemoveField(
            model_name='sessiontable',
            name='courseCode',
        ),
        migrations.DeleteModel(
            name='DeadLine',
        ),
        migrations.DeleteModel(
            name='SessionTable',
        ),
        migrations.AddField(
            model_name='sessioncoursetable',
            name='session_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoAuthentication.SessionNameTable'),
        ),
    ]
