# Generated by Django 2.2.2 on 2019-08-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAuthentication', '0036_auto_20190813_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionnametable',
            name='session_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
