# Generated by Django 2.2 on 2019-09-11 02:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAuthentication', '0037_auto_20190813_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionnametable',
            options={'ordering': ('-start_date',)},
        ),
        migrations.AlterField(
            model_name='sessionnametable',
            name='date_created',
            field=models.DateField(default=datetime.date(2019, 9, 11)),
        ),
        migrations.AlterField(
            model_name='sessionnametable',
            name='end_date',
            field=models.DateField(default=datetime.date(2019, 9, 11)),
        ),
        migrations.AlterField(
            model_name='sessionnametable',
            name='start_date',
            field=models.DateField(default=datetime.date(2019, 9, 11)),
        ),
        migrations.AlterField(
            model_name='studentmanagement',
            name='date_created',
            field=models.DateField(default=datetime.date(2019, 9, 11)),
        ),
        migrations.AlterField(
            model_name='studentmanagement',
            name='enrolled_year',
            field=models.DateField(default=datetime.date(2019, 9, 11)),
        ),
    ]
