# Generated by Django 2.2 on 2019-10-22 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAuthentication', '0038_auto_20190911_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grademanagement',
            name='internal_marks',
        ),
        migrations.RemoveField(
            model_name='grademanagement',
            name='total_marks',
        ),
        migrations.AlterField(
            model_name='sessionnametable',
            name='date_created',
            field=models.DateField(default=datetime.date(2019, 10, 22)),
        ),
        migrations.AlterField(
            model_name='sessionnametable',
            name='end_date',
            field=models.DateField(default=datetime.date(2019, 10, 22)),
        ),
        migrations.AlterField(
            model_name='sessionnametable',
            name='start_date',
            field=models.DateField(default=datetime.date(2019, 10, 22)),
        ),
        migrations.AlterField(
            model_name='studentmanagement',
            name='date_created',
            field=models.DateField(default=datetime.date(2019, 10, 22)),
        ),
        migrations.AlterField(
            model_name='studentmanagement',
            name='enrolled_year',
            field=models.DateField(default=datetime.date(2019, 10, 22)),
        ),
    ]
